LIB  = lvm-internal
SRCS = activate.c archive.c archiver.c btree.c cluster_locking.c config.c crc.c crc_gen.c dev-cache.c device.c dev-io.c dev-luks.c dev_manager.c dev-md.c dev-swap.c disk_rep.c disk-rep.c display.c errseg.c export.c external_locking.c file_locking.c filter.c filter-composite.c filter-md.c filter-mpath.c filter-persistent.c filter-regex.c filter-sysfs.c flags.c format1.c format_pool.c format-text.c freeseg.c fs.c import.c import_export.c import-export.c import-extents.c import_vsn1.c label.c layout.c locking.c log.c lv.c lvm1-label.c lv_manip.c lvmcache.c lvm-exec.c lvm-file.c lvm-globals.c lvm-percent.c lvm-string.c lvm-wrappers.c memlock.c merge.c metadata.c mirror.c mirrored.c no_locking.c pool_label.c properties.c pv.c pv_manip.c pv_map.c raid.c raid_manip.c replicator.c replicator_manip.c report.c segtype.c snapshot.c snapshot_manip.c striped.c str_list.c tags.c text_label.c thin.c thin_manip.c timestamp.c toolcontext.c unknown.c uuid.c vg.c vg_number.c zero.c

CFLAGS += -I../include -I../libdaemon/client -I../libdaemon/server

.include <bsd.lib.mk>
