LIB  = dm
SRCS = bitset.c dbg_malloc.c hash.c libdm-common.c libdm-config.c libdm-deptree.c libdm-file.c libdm-iface.c libdm-report.c libdm-string.c list.c matcher.c parse_rx.c pool.c pool-debug.c pool-fast.c ttree.c

CFLAGS += -I../include -I../lib -I. -DDM_DEVICE_UID=0 -DDM_DEVICE_GID=0 -DDM_DEVICE_MODE=384

.include <bsd.lib.mk>
